<?php
define("SERVER_NAME", "delta.djj.nsw.gov.au");
define("DB_SERVER", "localhost");
define("DB_NAME", "magic_spreadsheet");
define ("DB_USER", "software");
define ("DB_PASSWORD", "sh0wtime");
define("LOGIN_PAGE", "/login.php");
define("START_PAGE", "/index.php");
define("DENY_ACCESS_PAGE", "/denied.php");
define("ADMIN_MAIL", "italert@djj.nsw.gov.au");
define("ADMIN_NAME", "Juvenile Justice");
define("SYSTEM_NAME", "JJ IM&T Goodness");
define("SITE_OWNER", "NSW Department of Justice - Juvenile Justice");
define("SITE_ADDRESS1", "Level 2, Henry Deane Building 20 Lee St");
define("SITE_ADDRESS2", "Sydney NSW 2000");
define("LDAP_SERVER", "ldap.djj.nsw.gov.au");
define("BASE_CONTEXT", "O=DJJ");
?>
